# Generated by Django 3.1.2 on 2020-10-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('nickName', models.CharField(blank=True, default='', max_length=100)),
                ('avatarUrl', models.TextField()),
                ('gender', models.IntegerField()),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
