# Generated by Django 3.1.2 on 2020-10-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huinan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
